# A box for development/compiling code.

version: "3"

services:l
  dev:
    build:
      context: .
      dockerfile: docker/dev/Dockerfie
    working_dir: /app
    command: bash
    volumes:
      - "./:/app"