# Provides containers for building & compiling.

version: "3"

services:
  gobuilder:
    image: golang
    volumes:
    - "./:/app"
    - "./.cache/gocache:/.cache"
    working_dir: /app
    user: "${UID}"
  dashboardwebbuilder:
    image: node
    volumes:
    - "./web/dashboard:/app"
    working_dir: /app
    user: "${UID}"
