# This stack will bring up all the services needed to demonstrate a multi-node installation
# of the single execution process.

version: "3"

services:
  dashboard:
    build:
      context: .
      dockerfile: docker/dashboard/Dockerfile
    working_dir: /www
    ports:
    - "${DASHBOARD_HTTP_PORT}:80"
    volumes:
    - "./web/dashboard/templates:/www/templates"
    - "./web/dashboard/dist:/www/dist"
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "./docker-compose.yaml:/www/docker-compose.yaml"
    - "./.env:/www/.env"
  chain:
    build:
      context: .
      dockerfile: docker/chain/Dockerfile
    expose:
    - "${UDP_PORT}/udp"
    ports:
    - "${CHAIN_HTTP_PORT}:80"
    environment:
      CHAIN_PORT: "${UDP_PORT}"
  validator1:
    image: single-executor-validator
    ports:
      - "8010:80"
    environment:
      NODE_ID: 1
      CHAIN_UDP_ADDR: "chain:${UDP_PORT}"
      SIGN_INTERVAL: "${SIGN_INTERVAL}"
    volumes:
      - "./config/watchdog:/etc/watchdog"
  validator2:
    image: single-executor-validator
    environment:
      NODE_ID: 2
      CHAIN_UDP_ADDR: "chain:${UDP_PORT}"
      SIGN_INTERVAL: "${SIGN_INTERVAL}"
    ports:
      - "8011:80"
    volumes:
      - "./config/watchdog:/etc/watchdog"
  validator3:
    image: single-executor-validator
    environment:
      NODE_ID: 3
      CHAIN_UDP_ADDR: "chain:${UDP_PORT}"
      SIGN_INTERVAL: "${SIGN_INTERVAL}"
    ports:
      - "8012:80"
  validator4:
    image: single-executor-validator
    environment:
      NODE_ID: 4
      CHAIN_UDP_ADDR: "chain:${UDP_PORT}"
      SIGN_INTERVAL: "${SIGN_INTERVAL}"
    ports:
      - "8013:80"
  validator5:
    image: single-executor-validator
    environment:
      NODE_ID: 5
      CHAIN_UDP_ADDR: "chain:${UDP_PORT}"
      SIGN_INTERVAL: "${SIGN_INTERVAL}"
    ports:
      - "8014:80"
