# Time in milliseconds
minElectionTimeout: 3000   # 3s
maxElectionTimeout: 5000  # 5s
networkInterval: 10000    # 10s
heartbeatInterval: 1000
listenOn: "0.0.0.0:6000"

id: 2

peers:
  - id: 1
    address: "validator1:6000"
#  - id: 3
#    address: "validator3:6000"

command:
  command: yes